### ISSUE TITLE
Implement the Diffie–Hellman funnctions

### ISSUE THREAD

**Issue by arpi-r** [NJnisarg/tor_project#10]
## Subject
Implement the generation of DH private key and compute the DH shared key functions as outlined in the Tor Spec.
The link to spec is: [tor_spec](https://gitweb.torproject.org/torspec.git/tree/tor-spec.txt)
## Type
- Feature addition/removal
- Spec alignment

## Files to touch
This implementation will solely be in the `crypto/core_crypto` module. Under the `CoreCryptoDH` class, there are two functions already defined. Please add code to it. Also, you can add any required parameters and return a value as needed. 

## Steps to get started
- Go through the section `0.3. Ciphers` in the spec linked above. 
- Some variables/constants defined in the spec are already defined in `crypto/core_crypto`, feel free to add more if needed

## Details
- The `generate_dh_priv_key` function should return two values, x and g^x
- The `compute_dh_shared_key` function should return the shared key, g^xy. It takes g^x and y as input. 
- The value of g is specified in the spec. 
- Section `5.1.3. The "TAP" handshake` gives more information as to how DH is used in Tor.

**Comment by NJnisarg** [comment]
This is now complete. Its part of the stable_master branch at the time of writing this comment. I will close the issue
