### ISSUE TITLE
Create the RelayCell Base class

### ISSUE THREAD

**Issue by NJnisarg** [NJnisarg/tor_project#17]
## Subject
Create the base class for a `RelayCell` by extending the `Cell` class. This class will be used by different relay cells.

## Type
- Feature addition

## Files to touch
create the class in `relay_cell.py` in `cell` module

## Steps to get started
Thoroughly read the sections: `3`, `6` in the tor-spec.
Link to spec: [tor-spec](https://gitweb.torproject.org/torspec.git/tree/tor-spec.txt)

**Comment by adityasohoni** [comment]
I'll take up this issue
