### ISSUE TITLE
Create the RELAY_EXTEND2 Payload class

### ISSUE THREAD

**Issue by NJnisarg** [NJnisarg/tor_project#18]
## Subject
Create the `RelayExtendPayload` for `RELAY_EXTEND2` payload.
This is only the `data`(also called `relay payload`) section/field of the `RelayCell`, do not create the entire cell structure. Take guidelines from the `CreateCellPayload` class in `cell/control_cell.py`.

## Type
- Feature addition

## Files to touch
Create the class in the `cell/relay_cell.py` file.

## Expected Behavior
This class will act as an object in the `RelayCell` data/payload field.

## Steps to get started
Read the Tor Spec sections: `3`, `5.1`, `5.1.2`, `5.3`, `6`
Link to Tor Spec: [tor-spec](https://gitweb.torproject.org/torspec.git/tree/tor-spec.txt)

## Details
Create subclasses for nested objects. This given class might use other classes that are already created, look for those and don't create them again. Example: it will use `TapCHData` class for TAP handshake client data.

**Comment by lomadapraveenreddy** [comment]
I'll take up this issue.

**Comment by arpi-r** [comment]
@lomadapraveenreddy  What's the progress?

**Comment by lomadapraveenreddy** [comment]
Sorry for the delay I haven't seen the comment.I've written the payload class. Where should I keep this class. Is it in a new file?
