### ISSUE TITLE
Create the RELAY_EXTENDED2 Payload class

### ISSUE THREAD

**Issue by NJnisarg** [NJnisarg/tor_project#19]
## Subject
Create the `RelayExtendedPayload` for RELAY_EXTENDED2 payload.
This is only the data(also called relay payload) section/field of the `RelayCell`, do not create the entire cell structure. Take guidelines from the `CreatedCellPayload` class in `cell/control_cell.py.`

## Type
Feature addition

## Files to touch
Create the class in the `cell/relay_cell.py` file.

## Expected Behavior
This class will act as an object in the `RelayCell` data/payload field.

## Steps to get started
Read the Tor Spec sections: `3`, `5.1`, `5.1.2`, `5.3`, `6`
Link to Tor Spec: [tor-spec](https://gitweb.torproject.org/torspec.git/tree/tor-spec.txt)

## Details
Create subclasses for nested objects. This given class might use other classes that are already created, look for those and don't create them again. Example: it will use `TapSHData` class for TAP handshake server data.

**Comment by suhasks123** [comment]
I'll take up this issue

**Comment by arpi-r** [comment]
@suhasks123  What's the progress?

**Comment by suhasks123** [comment]
Working on it. I'll submit a pr in one or two days
