### ISSUE TITLE
Implementing the Relay Begin Cell

### ISSUE THREAD

**Issue by NJnisarg** [NJnisarg/tor_project#24]
## Subject
Implementation of the relay begin cell. This cell is used to start a TCP connection at the exit node. (Basically, connect to a website)
## Type
- Feature addition/removal

## Files to touch
Add the cell payload to `relay_cell.py` like the other cells

## Steps to get started
Go through the spec section `6.2`
Link to spec: [Tor Spec](https://gitweb.torproject.org/torspec.git/tree/tor-spec.txt)

## Details
Create the payload class. And for this task also implement the functions in the `cell_processing.py` for the `Builder`, `Parser` and the `Processor` classes

**Comment by suhasks123** [comment]
I'll take up this issue.
