### ISSUE TITLE
Implementing the Byte oriented message format

### ISSUE THREAD

**Issue by NJnisarg** [NJnisarg/tor_project#28]
## Subject
Implement the Cell serialization in a Byte oriented fashion instead of json string.
## Type
- Feature addition/removal

## Files to touch
Add functions to `Serialize` and `Deserialize` classes in the `cell/serializers.py` file

## Steps to get started
Look into the `struct` module of python to implement this feature
[Struct Module](https://docs.python.org/3.6/library/struct.html)
## Details
Create some serializer functions that take a Cell object and creates a byte stream message format that can be sent down a socket.
Also, create deserializer functions that takes a byte stream and convert it to a Python Cell object

**Comment by suhasks123** [comment]
I'll take up this issue

**Comment by NJnisarg** [comment]
This has been implemented. Closing the Issue
