### ISSUE TITLE
Implement hybrid encrypt function

### ISSUE THREAD

**Issue by NJnisarg** [NJnisarg/tor_project#3]
## Subject
Implement the hybrid encrypt function outlined in the Tor Spec.
The link to spec is: [tor_spec](https://gitweb.torproject.org/torspec.git/tree/tor-spec.txt)
## Type
- Feature addition/removal
- Spec alignment

## Files to touch
This implementation will solely be in the `crypto/core_crypto` module. Under the `CoreCryptoRSA` class, there is a function defined already. Please add code to it. Also, you can add any required params and return a value as needed. 

## Steps to get started
- Go through the section `0.4. A bad hybrid encryption algorithm, for legacy purposes.` in the spec linked above. 
- The variables/constants defined in the spec are defined already in the `crypto/core_crypto` itself, feel free to add more if you need

## Details
- The encrypted message should be a python dict converted to JSON string(using json module)
The fields of the python dict should be the different section in the `m1` and `m2` where the `m1` is the first part of the encrypted message and `m2` is the second part as mentioned in the spec.

**Comment by adityasohoni** [comment]
I'll take up this issue

**Comment by adityasohoni** [comment]
In the hybrid encrypt function, what is the best way to generate the random key K(int the spec)?  Can it just be a random number of appropriate range(for obtaining the desired length in binary) converted to binary?

**Comment by NJnisarg** [comment]
Have a look at this:
https://cryptography.io/en/latest/random-numbers/

**Comment by adityasohoni** [comment]
What should be the fields in the python dict that is to be converted to JSON and returned?
Should the nonce(in case 2) used for encrypting m2 with the stream cipher(the stream cipher uses AES, & AES uses a nonce)  also be included in the dict?

**Comment by NJnisarg** [comment]
Not actually sure. But currently the it has 4 fields in the dictionary. Padding bytes, symmetric key , m1 and m2. But whatever is required for decrypt you should back in the dictionary

**Comment by NJnisarg** [comment]
`For a stream cipher, unless otherwise specified, we use 128-bit AES in counter mode, with an IV of all 0 bytes.  (We also require AES256.)` 
IV = Initialization vector. 
I guess this is the nonce. The Spec keeps a fixed nonce. Correct me if I am wrong

**Comment by adityasohoni** [comment]
Yeah the IV is the nonce i guess, thanks
