### ISSUE TITLE
Implement creation of Random circuit ID

### ISSUE THREAD

**Issue by NJnisarg** [NJnisarg/tor_project#5]
## Subject
Implement the `get_rand_circ_id` function using the Tor Spec.
The link to spec is [tor_spec](https://gitweb.torproject.org/torspec.git/tree/tor-spec.txt)

## Type
- Feature addition/removal
- Spec alignment
## Files to touch
This implementation will be in the `onion_proxy/circuit` module. Under the `Circuit` class, there is a function defined already. Please add code to it. Also, you can add any required params and return a value as needed. Also, add similar code to the `onion_roter/onion_router` module, under the `OnionRouter` class, where the `get_rand_circ_id` function is defined again.

## Steps to get started
Go through the section `5.1.1. Choosing circuit IDs in create cells` in the spec linked above.

**Comment by suhasks123** [comment]
I'll take up this issue
